#!/usr/bin/env node
/**
 * maczo Lucky Spin — Provably Fair verifier (Node.js, zero dependencies)
 *
 * Reproduces EXACTLY the server algorithm (see ProvablyFairWheel.cs):
 *   commitment = SHA256(serverSeed)                                   (hex, lowercase)
 *   outcome    = HMAC-SHA256(key=serverSeed, msg="clientSeed:nonce:cursor")
 *              → read 8-byte big-endian words → rejection sampling over total weight
 *              → cumulative-weight walk → segment index
 *
 * The result is deterministic: same (serverSeed, clientSeed, nonce, weights) → same index.
 * After the site REVEALS a serverSeed (via "rotate"), you can re-run every spin you made
 * under it here and confirm it matches — and that SHA256(serverSeed) equals the commitment
 * that was shown to you BEFORE you spun.
 *
 * Usage:
 *   node verify.js --commit <hash> --server <seed> --client <seed> --nonce <n> --weights <json|@file>
 *   node verify.js --selftest            # run built-in test vectors
 *
 * `weights` = JSON array of the wheel segments (weight>0 only) IN PRIZE-TABLE ORDER, e.g.
 *   [{"value":0.1,"weight":300},{"value":0.2,"weight":250}, ...]
 * The returned segmentIndex indexes into that array (0-based).
 */
"use strict";
const crypto = require("crypto");

/** SHA-256 hex (lowercase) of a UTF-8 string = the commitment for a server seed. */
function sha256Hex(s) {
  return crypto.createHash("sha256").update(Buffer.from(s, "utf8")).digest("hex");
}

/**
 * Pick a wheel segment index from (serverSeed, clientSeed, nonce, weights).
 * weights: array of positive integers (segment weights, prize-table order).
 * Mirrors ProvablyFairWheel.SelectSegmentIndex — BigInt for uint64 exactness.
 */
function selectSegmentIndex(serverSeed, clientSeed, nonce, weights) {
  if (!Array.isArray(weights) || weights.length === 0) throw new Error("weights required");
  let total = 0n;
  for (const w of weights) {
    const bw = BigInt(w);
    if (bw < 0n) throw new Error("weight must be >= 0");
    total += bw;
  }
  if (total <= 0n) throw new Error("total weight must be > 0");
  if (weights.length === 1) return 0;

  const MAX_U64 = (1n << 64n) - 1n;
  const limit = MAX_U64 - (MAX_U64 % total); // largest unbiased boundary (kills modulo bias)
  const key = Buffer.from(serverSeed, "utf8");

  for (let cursor = 0; cursor < 1024; cursor++) {
    const msg = `${clientSeed}:${nonce}:${cursor}`;
    const hash = crypto.createHmac("sha256", key).update(Buffer.from(msg, "utf8")).digest(); // 32 bytes
    for (let off = 0; off + 8 <= hash.length; off += 8) {
      let word = 0n;
      for (let b = 0; b < 8; b++) word = (word << 8n) | BigInt(hash[off + b]); // big-endian uint64
      if (word >= limit) continue; // biased tail → reject
      const pick = word % total;
      let acc = 0n;
      for (let i = 0; i < weights.length; i++) {
        acc += BigInt(weights[i]);
        if (pick < acc) return i;
      }
      return weights.length - 1; // safety
    }
  }
  throw new Error("entropy exhausted (cursor > 1024)");
}

/** Full verification: commitment match + segment reproduction. */
function verify({ commitment, serverSeed, clientSeed, nonce, weights }) {
  const calcCommit = sha256Hex(serverSeed);
  const commitOk = !commitment || calcCommit.toLowerCase() === String(commitment).toLowerCase();
  const w = weights.map((s) => (typeof s === "object" ? Number(s.weight) : Number(s)));
  const index = selectSegmentIndex(serverSeed, clientSeed, Number(nonce), w);
  const seg = weights[index];
  return {
    commitmentMatches: commitOk,
    computedCommitment: calcCommit,
    segmentIndex: index,
    prizeValue: seg && typeof seg === "object" ? seg.value : undefined,
    prizeLabel: seg && typeof seg === "object" ? seg.label : undefined,
  };
}

// ── CLI ──
function parseArgs(argv) {
  const a = {};
  for (let i = 2; i < argv.length; i++) {
    const k = argv[i];
    if (k.startsWith("--")) { a[k.slice(2)] = (argv[i + 1] && !argv[i + 1].startsWith("--")) ? argv[++i] : true; }
  }
  return a;
}

function loadWeights(spec) {
  if (typeof spec !== "string") throw new Error("--weights required");
  const raw = spec.startsWith("@") ? require("fs").readFileSync(spec.slice(1), "utf8") : spec;
  const parsed = JSON.parse(raw);
  return Array.isArray(parsed) ? parsed : (parsed.segments || parsed.items);
}

// Built-in self-test vectors (generated by the reference implementation; also in test-vectors.json)
const SELFTEST = require("./test-vectors.json");

if (require.main === module) {
  const a = parseArgs(process.argv);
  if (a.selftest) {
    let pass = 0, fail = 0;
    for (const v of SELFTEST.vectors) {
      const got = selectSegmentIndex(v.serverSeed, v.clientSeed, v.nonce, v.weights.map((s) => s.weight ?? s));
      const commit = sha256Hex(v.serverSeed);
      const ok = got === v.expectedIndex && commit === v.commitment;
      console.log(`${ok ? "✅" : "❌"} nonce=${v.nonce} → index=${got} (want ${v.expectedIndex}) commit=${commit === v.commitment}`);
      ok ? pass++ : fail++;
    }
    console.log(`\n${pass} passed, ${fail} failed`);
    process.exit(fail ? 1 : 0);
  }
  if (!a.server || !a.client || a.nonce === undefined || !a.weights) {
    console.log("Usage: node verify.js --commit <hash> --server <seed> --client <seed> --nonce <n> --weights <json|@file>");
    console.log("       node verify.js --selftest");
    process.exit(2);
  }
  const res = verify({
    commitment: a.commit, serverSeed: a.server, clientSeed: a.client,
    nonce: Number(a.nonce), weights: loadWeights(a.weights),
  });
  console.log(JSON.stringify(res, null, 2));
  if (a.commit && !res.commitmentMatches) { console.error("\n❌ COMMITMENT MISMATCH — serverSeed does NOT hash to the published commitment!"); process.exit(1); }
  console.log(`\n✅ Segment #${res.segmentIndex}${res.prizeValue !== undefined ? ` = ${res.prizeValue} MC` : ""}${a.commit ? " · commitment verified" : ""}`);
}

module.exports = { sha256Hex, selectSegmentIndex, verify };
